package ruraldevs.beans;

public enum EstadosEnum {
    ACRE, ALAGOAS, AMAPA, AMAZONAS, BAHIA, CEARA, ESPÍRITO_SANTO, GOIAS, MARANHAO, MATO_GROSSO, MATO_GROSSO_DO_SUL, MINAS_GERAIS, PARA, PARAIBA, PARANA, PERNAMBUCO, PIAUI, RIO_DE_JANEIRO, RIO_GRANDE_DO_NORTE, RIO_GRANDE_DO_SUL, RONDONIA, RORAIMA, SANTA_CATARINA, SAO_PAULO, SERGIPE, TOCANTINS, DISTRITO_FEDERAL;
}
